import streamlit as st
import pandas as pd
import pickle
from disease_info import disease_details

# ----------------------------------
# Page Configuration
# ----------------------------------
st.set_page_config(
    page_title="AI Healthcare Diagnosis Assistant",
    page_icon="🏥",
    layout="wide"
)

# ----------------------------------
# Load CSS
# ----------------------------------
def load_css():
    try:
        with open("style.css") as f:
            st.markdown(
                f"<style>{f.read()}</style>",
                unsafe_allow_html=True
            )
    except:
        pass

load_css()

# ----------------------------------
# Sidebar
# ----------------------------------
with st.sidebar:

    st.image(
        "https://img.icons8.com/color/96/hospital-3.png",
        width=90
    )

    st.title("AI Healthcare")

    st.markdown("### 👩‍💻 Developer")
    st.success("Princi Soni")

    st.markdown("---")

    st.markdown("### 💻 Technologies")

    st.write("✅ Python")
    st.write("✅ Streamlit")
    st.write("✅ Machine Learning")
    st.write("✅ Scikit-Learn")
    st.write("✅ Pandas")

    st.markdown("---")

    st.info("Version : 1.0")

# ----------------------------------
# Title
# ----------------------------------

st.title("🏥 AI-Powered Healthcare Diagnosis Assistant")

st.write(
    "Select your symptoms and let AI predict the most probable disease."
)

st.divider()

# ----------------------------------
# Load Model
# ----------------------------------

model = pickle.load(open("models/disease_model.pkl", "rb"))
le = pickle.load(open("models/label_encoder.pkl", "rb"))

# ----------------------------------
# Load Dataset
# ----------------------------------

df = pd.read_csv("dataset/Training.csv")

symptoms = list(df.columns[:-1])

# ----------------------------------
# Symptom Selection
# ----------------------------------

st.subheader("🩺 Select Symptoms")

selected_symptoms = st.multiselect(
    "Choose Symptoms",
    symptoms
)

st.write(f"Selected Symptoms : {len(selected_symptoms)}")

st.divider()

# ----------------------------------
# Prediction
# ----------------------------------

if st.button("🔍 Predict Disease"):

    if len(selected_symptoms) == 0:
        st.warning("Please select at least one symptom.")
        st.stop()

    input_data = [0] * len(symptoms)

    for symptom in selected_symptoms:
        input_data[symptoms.index(symptom)] = 1

    prediction = model.predict([input_data])

    disease = le.inverse_transform(prediction)

    disease_name = disease[0]

    st.success("Predicted Disease")

    st.subheader(f"🦠 {disease_name}")

    st.divider()
    
    # ----------------------------------
    # Disease Information
    # ----------------------------------

    if disease_name in disease_details:

        info = disease_details[disease_name]

        col1, col2 = st.columns(2)

        with col1:

            st.subheader("💊 Recommended Medicine")
            st.success(info["medicine"])

            st.subheader("🥗 Recommended Diet")
            st.info(info["diet"])

        with col2:

            st.subheader("🛡️ Precautions")
            st.warning(info["precautions"])

            st.subheader("👨‍⚕️ Doctor to Consult")
            st.success(info["doctor"])

    else:

        st.info(
            "Disease predicted successfully. Detailed medicine, diet and precautions will be available after updating the disease database."
        )

    st.divider()

    st.subheader("📋 Selected Symptoms")

    for symptom in selected_symptoms:
        st.write("✅", symptom)
        
# ----------------------------------
# Footer
# ----------------------------------

st.divider()

st.markdown("""
### ⚠️ Medical Disclaimer

This application is developed for educational purposes only.

The prediction generated by this AI model is based on the symptoms selected by the user and should **not** be considered a final medical diagnosis.

Always consult a qualified healthcare professional before taking any medicine or treatment.
""")

st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    st.success("👩‍💻 Developed by: Princi Soni")

with col2:
    st.info("🎓 B.Tech CSE (AI & ML)")

st.markdown(
    """
    <div style="text-align:center; color:gray;">
        <h4>🏥 AI-Powered Healthcare Diagnosis Assistant</h4>
        <p>Made with ❤️ using Python, Streamlit & Machine Learning</p>
    </div>
    """,
    unsafe_allow_html=True
)